### ISSUE TITLE
Slack Workspace for Project?

### ISSUE THREAD

**Issue by yuorme** [yuorme/covid-projections#24]
Been feeling pretty under the weather recently and am not as used to using Github for managing projects. Sorry for the oftentimes slow communication. Would there be interest in creating a slack? @patrickvossler18 @andrewgconnors @lossyrob @evkeane

**Comment by patrickvossler18** [comment]
Slack works for me! There's no rush on my end; staying healthy is much more important.

**Comment by lossyrob** [comment]
Feel free to use CovidCareMap's Gitter as well: https://gitter.im/covid19-healthsystemcapacity/community just to have something with the least amount of setup time. We've already pointed out your project there and there is a number of interested folk that would appreciate any conversations/may be interested in helping out.

If you want help setting up your own Gitter I'm happy to. IMO, Gitter channels for GitHub projects are pretty easy to set up and easier for broader engagement (as opposed to having to invite everyone to a slack channel). Gitter is def not as good as slack but for FOSS development that's my go-to.

Feel better and thank you a ton for open sourcing the work!

**Comment by andrewgconnors** [comment]
Yeah, I’m open to using whatever platform is convenient for you! No real preference here.

**Comment by evkeane** [comment]
I'd certainly find that helpful David. Still learning the ropes on github
myself.

Evin

**Comment by yuorme** [comment]
@lossyrob thanks for suggesting gitter. Looking into it a bit more, I think it could be the best solution since it's already well integrated with Twitter/Github. The only thing I'd like to have is different channels for front-end and back-end work. Would that be possible?

**Comment by lossyrob** [comment]
That's possible. However, I'd suggest just sticking with one room - in my experience it's a lot easier to track only one room, and usually conversations are spotty through time, so there's space to have conversations about backend, frontend, higher level discussions etc that can draw more participation if people only have to join one instead of several rooms.

**Comment by lossyrob** [comment]
Another way to track work-specific conversation is to write GitHub issues that are a bit more broad, on a topic. e.g. "Backend Design". People can comment there and know to look there for updates on progress. In the early days of CovidCareMap I was also taking things people said in Gitter and placing them into issues (and linking to the Gitter chat, which you can do on a message basis) if the conversation should be tracked as part of an issue.

**Comment by yuorme** [comment]
Just created gitter and you all should have an invite. Closing this issue for now.
