### ISSUE TITLE
Investigate duplicate rows in LANL confirmed cases dataset

### ISSUE THREAD

**Issue by yuorme** [yuorme/covid-projections#29]
LANL confirmed cases seem to have duplicate rows for every `date`, `fcst_date`, and `state`. This is not the case for the deaths csv file. What are the reasons for this and can we safely clean up by taking the maximum value at each date?

![image](https://user-images.githubusercontent.com/7991877/79710691-caa78100-8293-11ea-9bb2-6f2fc804683b.png)
![newplot (6)](https://user-images.githubusercontent.com/7991877/79710708-d4c97f80-8293-11ea-9c14-4617caad0429.png)

**Comment by andrewgconnors** [comment]
I think this is a sneaky bug in get_lanl_df() where the df_list still contains the dataframes for deaths and those get concat'd together with the confirmed cases dataframes on line 62 of projections-scraper.py

**Comment by yuorme** [comment]
That's probably it, I'll take a look at the code tonight :)
